# Generated by Django 4.1.5 on 2023-02-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amedia_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="last_watched_episode",
            field=models.IntegerField(null=True),
        ),
    ]
